TARGET          := liballegrogl
SOURCES         := src
CFILES   := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.c))
CPPFILES := $(foreach dir,$(SOURCES), $(wildcard $(dir)/*.cpp))
OBJS     := $(CFILES:.c=.o) $(CPPFILES:.cpp=.o)

PREFIX  = arm-vita-eabi
CC      = $(PREFIX)-gcc
CXX     = $(PREFIX)-g++
AR      = $(PREFIX)-gcc-ar
CFLAGS  = -g -Wl,-q -O3 -ffast-math -mtune=cortex-a9 -mfpu=neon -Wno-incompatible-pointer-types -Wno-stringop-overflow
ASFLAGS = $(CFLAGS)
LIBS = -lalleg

INC = -I . -I include -I include/allegrogl -I include/allegrogl/GLext -I include/GL
DEFS = -DPSVITA -DALLEGRO_PSV

CFLAGS += $(INC) $(DEFS)

CXXFLAGS  = $(CFLAGS) -fexceptions -std=gnu++11 -Wno-write-strings

all: $(TARGET).a

$(TARGET).a: $(OBJS)
	$(AR) -rc $@ $^
	
%.smpc:
	@make -C $(@:.smpc=) clean
	
%.smp:
	@make -C $(@:.smp=)
	ls -1 $(@:.smp=)/*.vpk | xargs -L1 -I{} cp {} .
	
clean: 
	@rm -rf $(TARGET).a $(TARGET).elf $(OBJS)
	
install: $(TARGET).a
	@mkdir -p $(VITASDK)/$(PREFIX)/lib/
	cp $(TARGET).a $(VITASDK)/$(PREFIX)/lib/
	
